export const localAPI = [
    {
        id: 1,
        name: "Llavero Gatito",
        price: 250,
        category: "llaveros",
        img: "gatitos.jpg",
        description: "Un Llavero Gatito que se adapta a vos",
        stock: 6,
    },
    {
        id: 2,
        name: "Kuromi",
        price: 1600,
        category: "figuras",
        img:"neko.jpg",
        description: "Un gato que se adapta a vos",
        stock: 6,
    },
    {
        id: 3,
        name: "Stand para Auriculares",
        price: 1100,
        category: "organizadores",
        img:"auris.jpg",
        description: "Un soporte de auricular que se adapta a vos",
        stock: 6,
    },
    {
        id: 4,
        name: "Soporte Celular",
        price: 370,
        category: "organizadores",
        img:"celu.jpg",
        description: "Un soporte de celular que se adapta a vos",
        stock: 6,
    },
    {
        id: 5,
        name: "Stand para Notebook",
        price: 1400,
        category: "organizadores",
        img:"compu.jpg",
        description: "Un soporte de laptop que se adapta a vos",
        stock: 6,
    },
    {
        id: 6,
        name: "Kurama",
        price: 2000,
        category: "figuras",
        img:"kurama.jpg",
        description: "Un kurama que se adapta a vos",
        stock: 6,
    },
    {
        id: 7,
        name: "Raptor",
        price: 250,
        category: "articulados",
        img:"raptor.jpg",
        description: "Un Raptor que se adapta a vos",
        stock: 6,
    },
    {
        id: 8,
        name: "Mariposa",
        price: 250,
        category: "articulados",
        img:"mariposa.jpg",
        description: "Una Mariposa que se adapta a vos",
        stock: 6,
    },
    {
        id: 9,
        name: "Pardo",
        price: 250,
        category: "articulados",
        img:"pardo.jpg",
        description: "Un Pardo que se adapta a vos",
        stock: 6,
    },
    {
        id: 10,
        name: "Pterodactilo",
        price: 250,
        category: "articulados",
        img:"pterodactilo.jpg",
        description: "Un Pterodactilo que se adapta a vos",
        stock: 6,
    },
    {
        id: 11,
        name: "Triceraptop",
        price: 250,
        category: "articulados",
        img:"tricerapto.jpg",
        description: "Un Triceraptop que se adapta a vos",
        stock: 6,
    },
    {
        id: 12,
        name: "Lagartija",
        price: 250,
        category: "articulados",
        img:"pejelagarto.jpg",
        description: "Una Lagartija que se adapta a vos",
        stock: 6,
    },
    {
        id: 13,
        name: "Maceta Torre",
        price: 450,
        category: "jardineria",
        img:"macetatorre.jpg",
        description: "Unas Maceta Torre que se adapta a vos",
        stock: 6,
    },
    {
        id: 14,
        name: "No Face",
        price: 350,
        category: "figuras",
        img:"noface.jpg",
        description: "Un No Face que se adapta a vos",
        stock: 6,
    },
    {
        id: 15,
        name: "Kirara",
        price: 200,
        category: "figuras",
        img:"kirara.jpg",
        description: "Una Kirara que se adapta a vos",
        stock: 6,
    },
    {
        id: 16,
        name: "Maceta Baby Groot",
        price: 620,
        category: "jardineria",
        img:"macetagroot.jpg",
        description: "Una Maceta Baby Groot que se adapta a vos",
        stock: 6,
    },
    {
        id: 17,
        name: "Baby Yoda",
        price: 550,
        category: "figuras",
        img:"babyyoda.jpg",
        description: "Un Baby Yoda que se adapta a vos",
        stock: 6,
    },
    {
        id: 18,
        name: "Maceta Portal",
        price: 600,
        category: "jardineria",
        img:"macetaportal.jpg",
        description: "Una Maceta Portal que se adapta a vos",
        stock: 6,
    },
    {
        id: 19,
        name: "Pokebola Porta Cartuchos Switch",
        price: 750,
        category: "organizadores",
        img:"pokebola.jpg",
        description: "Una Pokebola Porta Cartuchos Switch que se adapta a vos",
        stock: 6,
    },
    {
        id: 20,
        name: "Llavero Harry Styles",
        price: 250,
        category: "llavero",
        img:"llaveroharry.jpg",
        description: "Un Llavero Harry Styles que se adapta a vos",
        stock: 6,
    },
    {
        id: 21,
        name: "Calabazas",
        price: 250,
        category: "aritos",
        img:"calabazas.jpg",
        description: "Unas Calabazas que se adapta a vos",
        stock: 6,
    },
    {
        id: 22,
        name: "Picador Estrella de la Muerte",
        price: 250,
        category: "figuras",
        img:"picador.jpg",
        description: "Un Picador Estrella de la Muerte que se adapta a vos",
        stock: 6,
    }
]